### ISSUE TITLE
Improve registers description, code and add enum for multi byte

### ISSUE THREAD

**Issue by Andrei-Basarab** [dsvensson/cc1101#42]
Improve a bit on registers module:
- [x] Move `PATABLE` and `FIFO` from `Command` to a new `MultiByte` enum
- [x] Improve `addr` methods of register enum types
- [x] Improve `raddr` and `waddr` methods of `Register` type

**Comment by dsvensson** [comment]
Right... PATABLE has some nice table data in the documentation pdf that perhaps deserves to be integrated somehow, or perhaps it was from data extracted from the windows application. It's been a while since I looked into it.

**Comment by Andrei-Basarab** [comment]
I will close this issue. Regarding the next PATABLE functionalities, that will be a job for another PR (I haven't done it yet).
I think to keep things simple, I will create tickets only for some uncharted features or for more complex ones.
For my planned work, I will only open PRs.
